name: 📝 New Post
description: Create a new post for the Yükisan Fan Club
title: "[POST] "
labels: ["new-post"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Post
        Fill in the details below to create a new post!
        
        **Important:** 
        - You must edit the title above to add your post text after "[POST] "
        - You must drag & drop at least one image in the Content field below
        
  - type: input
    id: access-code
    attributes:
      label: Access Code
      description: Enter the access code to post (will be hidden after verification)
      placeholder: "Enter access code"
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content
      description: Drag and drop at least one image here! (Required)
      placeholder: "Drag & drop your image(s) here..."
    validations:
      required: true
