name: 📝 New Post
description: Create a new post for the Yükisan Fan Club
title: "[POST] "
labels: ["new-post"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Post
        Fill in the details below to create a new post!
        
  - type: input
    id: access-code
    attributes:
      label: Access Code
      description: Enter the access code to post
      placeholder: "Enter access code"
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content
      description: What's happening? You can drag and drop images directly here!
      placeholder: "Describe your post... (tip: drag & drop images right into this box!)"
    validations:
      required: true
